export const FETCH_USER = 'FETCH_USER'

export const FETCH_REALTIME_USER_DB = 'FETCH_REALTIME_USER_DB'

export const FETCH_FIREBASE_DB = 'FETCH_FIREBASE_DB'

export const SET_WORKER = 'SET_WORKER'

export const LISTEN_ADDED_DATA_TO_CHILD = 'LISTEN_ADDED_DATA_TO_CHILD'

export const SET_MARKER = 'SET_MARKER'

export const SET_TIME = 'SET_TIME'

export const SET_PATH = 'SET_PATH'